version: '3.7'
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - '5050:5432'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password



